print(input("Name:dhanalakshmi"))
print(input("Email:dhanalakshmi2002v@gmail.com"))
print(input("Phone:9600493572"))
print(input("Education:Bsc.forensic science"))
print(input("Skills:excel,word,powerpoint,laboratory handling"))
print(input("Projects:types of hydrocarbon detection,fire and arson investigation"))
print(input("Certificate:IELTS exam,research writing internship"))
